setup_twitter_oauth("Niz0CCufq3NwzHXFrcuq1i3Mf", "QthX3LcN0HgnYUvqk9xU4FHJdOkPaz7dvTDcbyPfn6y5ydtU3Q", access_token='474841905-EKXO66VSjBSLrLflGdqydB7CgQqmYjj923maxqeZ', access_secret='ActGfbs0yyJMBY0kSDmINlxlw8jFfLC0E7aeUnV8Nqa9n')
searchTerm <- "#opioid"
searchResults <- searchTwitter(searchTerm, n = 1000)
tweetFrame <- twListToDF(searchResults)
userInfo <- lookupUsers(tweetFrame$screenName)
userFrame <- twListToDF(userInfo)
locatedUsers <- !is.na(userFrame$location)
locations <- geocode(userFrame$location[locatedUsers])
write.csv(locations, "locations.csv")
interpretedPlace <- subset(locations, select =c("interpretedPlace"))
write.csv(interpretedPlace, "interpretedPlace.csv")
ny <- read.csv("NewYork Data.csv")
ny_year_sum <- ddply(ny, .(Year), numcolwise(sum))
library(dplyr)
ny_year_sum <- ddply(ny, .(Year), numcolwise(sum))
library(plyr)
ny_year_sum <- ddply(ny, .(Year), numcolwise(sum))
write.csv(ny_year_sum, "ny_year_sum.csv")
ny_indicator_sum <- ddply(ny, .(Indicator), numcolwise(sum))
write.csv(ny_indicator_sum, "ny_indicator_sum.csv")
ny_month_sum <- ddply(ny, .(Month), numcolwise(sum))
write.csv(ny_month_sum, "ny_month_sum.csv")